/** Auto-generated by scripts/generate-image-assets.mjs — do not edit by hand */
export const IMAGE_ASSETS = {
  'IMG-001': {
    title: '가시설 계측 전체 개념도',
    webp: 'assets/images/technology/IMG-001_가시설-계측-전체-개념도_굴착단면계측항목.webp',
    alt: '가시설 계측 전체 개념도 - 굴착 단면 개요 — [좌]인접건물|배면|벽체|[우]굴착측, 흐름도 금지',
    caption: '가시설 계측 전체 개념도 — 굴착 단면과 대표 계측 항목(지중·수위·지보재·지표·인접구조물)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-001',
    prohibitedErrors: [
      '건물 기초 아래 굴착 공동·배면 빈 공간',
      '버팀보·굴착저가 배면·건물 아래',
      '옥상 자동광파기 본체·「자동광파기 측정(프리즘)」 라벨',
      '구조물경사계 지반 속·말뚝 형태'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-002': {
    title: '흙막이 계측 설치 대표 단면도',
    webp: 'assets/images/technology/IMG-002_흙막이-계측-설치-대표-단면도.webp',
    alt: '흙막이 계측 설치 대표 단면도 - [좌]인접건물|배면|벽체|[우]굴착 단면+11종 계측기(데이터로거 포함), 흐름도 금지',
    caption: '흙막이 계측 설치 대표 단면도 — [좌]인접건물|배면|벽체·띠장|[우]굴착측 단면과 11종 계측기(데이터로거 포함) 배치',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-002',
    prohibitedErrors: [
      '건물 기초 아래 굴착 공동·배면 빈 공간',
      '버팀보·굴착저가 배면·건물 아래',
      '옥상 자동광파기 본체·「자동광파기 측정(프리즘)」 라벨',
      '구조물경사계 지반 속·말뚝 형태',
      '인접건물을 지하에 묻힌 것처럼 표현',
      '지하수위계를 벽체 부착 센서로 표현',
      '간극수압계를 지하수위 관측공으로 표현',
      '하중계를 지반 내부에 배치',
      '토압계 감지면·작용 방향 누락',
      '굴착측·배면 지반 혼동',
      '어스앵커 강연선·T가 굴착측(공중)으로 향함',
      '앵커 하중계 반력판–헤드–텐던 조립 미표현',
      '어스앵커 하중계 수평(3~9시) 배치 (ANC-CLOCK)',
      'G.W.L이 굴착저 위인데 차수·배수 없이 굴착 건조',
      '지중경사계 Base — 활동면/영향 심도 하부 안정층 미도달·임의 m 일반화',
      '버팀보 하중계를 보 정중앙에 배치',
      'SOE 혼합형·지보체계 정체성 불명',
      '지중경사계·지하수위·간극수압 CIP/벽체 내부 매설 (SOE-INST-01)',
      '침하핀·측점에 「지표침하계」 라벨 (SETTLE-01)',
      '자동 지표침하계 침하판 주변 콘크리트 패드·해칭 (SETTLE-PLATE-01)',
      '앵커 LC ≠ 굴착측 두부',
      'IPI·지하수위·간극수압 배면 천공 위반',
      '⑦ 지표침하 측점에 지표침하계 라벨',
      '진동현식 라벨'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-003': {
    title: '버팀보 하중계 설치 개념도',
    webp: 'assets/images/technology/IMG-003_버팀보-하중계-설치-개념도_띠장접합부축압축.webp',
    alt: '버팀보 하중계 설치 개념도 - 띠장–버팀보 접합부(끝단) 축압축력 하중계 설치 — 보 정중앙 금지',
    caption: '버팀보 하중계 설치 개념도 — 띠장 접합부(끝단) 축압축력, 정중앙 설치 금지',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-003',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-004': {
    title: '어스앵커 하중계 설치 개념도',
    webp: 'assets/images/technology/IMG-004_어스앵커-하중계-설치-개념도_앵커두부정착구.webp',
    alt: '어스앵커 하중계 설치 개념도 - 굴착측 노출 앵커 두부 하중계(지지링·반력판–하중계–앵커헤드–강연선) 구성',
    caption: '어스앵커 하중계 설치 개념도 — 굴착측 노출 앵커 두부 하중계(지지링·반력판–하중계–앵커헤드–강연선) 구성',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-004',
    prohibitedErrors: [
      '하중계를 지반 내부에 배치',
      '정착장·그라우트체 내부에 하중계',
      '자유장 중간에 하중계 삽입',
      '반력판 없이 벽체 직접 부착',
      '인장력 T와 압축 반력 P를 단일 화살표로 혼동',
      'P=T 단일 표기 (ANC-AXIS)',
      '수평 버팀보형 앵커 두부 (ANC-AXIS)',
      '어스앵커 하중계 수평(3~9시) 배치 (ANC-CLOCK)',
      '앵커 강연선이 굴착측(공중)으로 향함',
      '설치도 하단 서버·모바일 데이터 흐름도 (P0-4)',
      '하중계 지반·정착장 내부',
      '자유장 중간 하중계',
      '앵커 시계 3시/9시 오류'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-005': {
    title: '주변건물 균열·경사 계측도',
    webp: 'assets/images/technology/IMG-005_주변건물-균열-경사-계측도_굴착주변건물배치.webp',
    alt: '주변건물 균열·경사 계측도 - 굴착 주변 건물의 균열계와 경사계 배치',
    caption: '주변건물 균열·경사 계측도 — 굴착 주변 건물의 균열계와 경사계 배치',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-005',
    prohibitedErrors: [
      '건물↔벽체 이격 L 구간 허공·배면 토사 없음',
      '건물 기초가 굴착저 높이 — 원 지표면 위 안착 아님',
      '지층이 굴착저에서만 시작 — 건물 아래 단절',
      '배면 거동→건물 변위 인과 불성립',
      '「경사계」 단독 라벨 — 지중경사계 혼동',
      '구조물경사계를 지주·포스트에 설치 (외벽 표면 부착 아님)',
      '「자동광파기 측정(프리즘)」 복합 라벨',
      '§3.1 배면·굴착 공간 역전 (건물 부양)',
      '배면 지표침하핀·T자 측점 (SETTLE-01)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-006': {
    title: '굴착 단계별 계측 흐름도',
    webp: 'assets/images/technology/IMG-006_굴착-단계별-계측-흐름도_1단계최종굴착계측.webp',
    alt: '굴착 단계별 계측 흐름도 - 4단계 굴착저면·지중경사계·지하수위·어스앵커 하중계',
    caption: '굴착 단계별 계측 흐름도 v3 — 4단계·IPI·G.W.L·어스앵커 LC(③④)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-006',
    prohibitedErrors: [
      '버팀보·지반앵커·지보재 하중계',
      '수평(3·9시)·5시 앵커 관통',
      '지중·굴착공중 하중계',
      'IMG-002와 동일 대표 단면도 역할 중복',
      '누적변위 그래프·로거 제품 사진 hero',
      '생성 시 로고·워터마크'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-007': {
    title: '터널 계측 전체 개념도',
    webp: 'assets/images/technology/IMG-007_터널-계측-전체-개념도_NATM단면주요계측항목.webp',
    alt: '터널 계측 전체 개념도 - NATM 터널 단면과 주요 계측 항목 표시',
    caption: '터널 계측 전체 개념도 — NATM 터널 단면과 주요 계측 항목 표시',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-007',
    prohibitedErrors: [
      '천단침하와 내공변위 동일 측선',
      '지중변위계를 록볼트처럼 표현',
      '단일 센서가 터널 전체 거동 대표',
      '숏크리트·강지보 응력계 동일 센서 표현'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-008': {
    title: '터널 전단면 내공변위 측정시스템',
    webp: 'assets/images/technology/IMG-008_터널-전단면-내공변위-측정시스템_상부아치내공변위.webp',
    alt: '터널 전단면 내공변위 측정시스템 - 내공변위계 Kit 체인으로 상부 아치 전단면 변위 프로파일 산정 원리 설명',
    caption: '터널 전단면 내공변위 — 상부 아치 P1~P5 Kit, Extension Tube, 노반(도로·철도) 미계측',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-008',
    prohibitedErrors: [
      '천단침하계처럼 상하 측정',
      'ACE-TCS를 2점 거리만으로 표현',
      'Extension Tube 체인 누락',
      '센서가 터널 중앙에 부유',
      '라이닝 연속 센서 튜브형 내공변위',
      'Kit가 전체 변형 프로파일 자동 산정',
      'P1~P5만으로 전단면 대표 표현'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-009': {
    title: '록볼트 축력·숏크리트 응력 계측도',
    webp: 'assets/images/technology/IMG-009_록볼트-축력-숏크리트-응력-계측도_지보재거동센서.webp',
    alt: '록볼트 축력·숏크리트 응력 계측도 - 지보재 거동 계측 위치와 센서 표현',
    caption: '록볼트 축력·숏크리트 응력 계측도 — 지보재 거동 계측 위치와 센서 표현',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-009',
    prohibitedErrors: [
      '숏크리트·변형률계 공중 부유 아이콘'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-010': {
    title: '터널 지표침하 계측도',
    webp: 'assets/images/technology/IMG-010_터널-지표침하-계측도_침하계자동광파기배치.webp',
    alt: '터널 지표침하 계측도 - 터널 상부 지표 침하계와 자동광파기 배치',
    caption: '터널 지표침하 계측도 — 터널 상부 지표 침하계와 자동광파기 배치',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-010',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-011': {
    title: '교량 계측 전체 개념도',
    webp: 'assets/images/technology/IMG-011_교량-계측-전체-개념도_상부구조교각교대기초.webp',
    alt: '교량 계측 전체 개념도 - 사장교형 10종(변형률·처짐·케이블장력·경사·기초침하 등)',
    caption: '교량 계측 전체 개념도 v3 — 사장교·상부구조→받침→교각/교대→기초, 10종 계측',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-011',
    prohibitedErrors: [
      '흙막이·굴착 단면 (BRI-01)',
      '종·횡변위 3축 주계측',
      '일반 거더교·사장교 혼재',
      '⑩ 침하·광파 단일 아이콘 혼동',
      '우측 패널 내부 감사 코드 노출',
      '생성 시 로고·워터마크'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-012': {
    title: '교각 변위·경사 계측도',
    webp: 'assets/images/technology/IMG-012_교각-변위-경사-계측도_상하부경사계변위계.webp',
    alt: '교각 변위·경사 계측도 - 교각 상하부 경사계와 변위계 설치 표현',
    caption: '교각 변위·경사 계측도 — 교각 상하부 경사계와 변위계 설치 표현',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-012',
    prohibitedErrors: [
      '교각 측면 단독 수평 변위계 (BRI-PIER-01)',
      '변위계에 기준·상대측정 대상 없음 (BRI-PIER-02)',
      '절대변위 ATS·프리즘 미표현 (BRI-PIER-04~05)',
      '기준점이 기초·말뚹캡 바로 옆 (BRI-PIER-06)',
      '상·하부 경사계 Δθ 회전 개념 누락 (BRI-PIER-07)',
      '기초 지표침하계·부등침하 미표현 (BRI-PIER-08)',
      '우측 데이터 흐름도 (BRI-PIER-09)',
      '관리기준 그래프 일반 수치 mm·° (BRI-PIER-10)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-013': {
    title: '교량 기초 침하 계측 배치도',
    webp: 'assets/images/technology/IMG-013_교량-기초-침하-계측도_침하계수위계변위계.webp',
    alt: '교량 기초 침하 계측 배치도 - 기초·교각·주변 지반 침하 측점, 지표침하계, ATS, 지하수위계(보조) 배치',
    caption: '교량 기초 침하 계측 배치도 — 침하 측점·지표침하계·자동광파기·지하수위계(보조)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-013',
    prohibitedErrors: [
      '기초 모서리 「침하계」 T자·작은 장치 (BRI-FND-01)',
      '침하 측점·지표침하계 미구분 (BRI-FND-02~03)',
      '수위계 주계측 과대 (BRI-FND-04)',
      '교각 측면 단독 변위계 (BRI-FND-05)',
      '기준점이 기초 근처 (BRI-FND-06)',
      '평면도 침하계 아이콘 (BRI-FND-07)',
      '침하 그래프 보편 mm 임계 (BRI-FND-08)',
      '우측 데이터 흐름도 (BRI-FND-09)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-014': {
    title: '교량 신축이음부 신축량 계측도',
    webp: 'assets/images/technology/IMG-014_교량-신축이음부-신축량-계측도_신축이음계핑거형.webp',
    alt: '교량 신축이음부 신축량 계측도 - 핑거형 신축이음·신축이음계 설치',
    caption: '교량 신축이음량 — 신축이음계·늘음량·줄음량',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-014',
    prohibitedErrors: [
      'X/Y/Z 3축 변위 표현 (BRI-EJ-01)',
      '종·횡·개폐량 병렬 주계측 (BRI-EJ-01)',
      '임의 관리기준 mm 표 (BRI-EJ-08)',
      '대형 데이터 흐름도 (BRI-EJ-09)',
      '핑거형 신축이음 미표현 (BRI-EJ-05)',
      '부유 센서·지그 미표현 (BRI-EJ-04)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-015': {
    title: '사면 계측 전체 개념도',
    webp: 'assets/images/technology/IMG-015_사면-계측-전체-개념도_활동면지중경사계지하수위계.webp',
    alt: '사면 계측 전체 개념도 - 활동면, 센서형 다단식 지중경사계, 지하수위계 배치',
    caption: '사면 계측 전체 개념도 — IPI·침하계·지하수위·간극수압(주) · (선택) 광학망',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-015',
    prohibitedErrors: [
      '사면 꼭대기·활동 구간에 자동광파기 본체',
      '지중경사계 Base가 활동면만 간신히 통과',
      '간극수압계가 G.W.L 위·수평 누운 형태',
      '수평변위 화살표 좌우 지그재그',
      '사면에 광파기·부동점에 측점 역전',
      '확정 원호 활동면',
      '활동면 아래 3~5m 일반값'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-016': {
    title: '원호활동면 계측 해석도',
    webp: 'assets/images/technology/IMG-016_원호활동면-계측-해석도_원호파괴지중경사계프로파일.webp',
    alt: '원호활동면 계측 해석도 - 원호파괴와 센서형 다단식 지중경사계 변위 프로파일 관계',
    caption: '원호활동면 계측 해석도 — 원호파괴와 센서형 다단식 지중경사계 변위 프로파일 관계',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-016',
    prohibitedErrors: [
      '최대 변위 깊이 = 활동면 위치',
      '지중경사계 단독으로 원호활동면 확정',
      '추정선과 실측선 동일 의미'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-017': {
    title: '평면활동면 계측 해석도',
    webp: 'assets/images/technology/IMG-017_평면활동면-계측-해석도_암반사면평면파괴.webp',
    alt: '평면활동면 계측 해석도 - 암반사면 평면파괴와 계측기 배치',
    caption: '평면활동면 계측 해석도 — 암반사면 평면파괴와 계측기 배치',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-017',
    prohibitedErrors: [
      '무한사면 안정식으로 활동면 확정',
      '변위 최대지점 = 평면활동면 단정',
      '간극수압 U 단순 상향 화살표만'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-018': {
    title: '강우-지하수위-변위 상관도',
    webp: 'assets/images/technology/IMG-018_강우-지하수위-변위-상관도_강우후수위상승변위증가.webp',
    alt: '강우-지하수위-변위 상관도 - 강우 후 수위 상승과 변위 증가 흐름',
    caption: '강우-지하수위-변위 상관도 — 강우 후 수위 상승과 변위 증가 흐름',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-018',
    prohibitedErrors: [
      '상관=인과 확정',
      '고정 지연시간'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-019': {
    title: '연약지반 성토부 계측기 설치 배치도',
    webp: 'assets/images/technology/IMG-019_연약지반-계측-전체-개념도_성토침하간극수압측방유동.webp',
    alt: '연약지반 성토부 계측기 설치 배치도 - Sand Mat·지표침하판·핀·IPI·간극수압·지중침하',
    caption: '연약지반 성토부 계측기 설치 배치도 v3 — IPI·piezo tip·지중침하·지하수위·토압',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-019',
    prohibitedErrors: [
      '간극수압계를 침하계처럼 표현',
      '측방유동 단순 수평화살표만',
      '성토고 H 고정 관리기준',
      '성토→압밀→침하 흐름 누락',
      '흐름도·인포그래픽 주형·센서 아이콘 나열',
      '데이터 로거·서버·모바일 UI',
      '지표침하핀·판에 지표침하계 라벨',
      '간극수압계를 지하수위계처럼 긴 관측공',
      '지중경사계 과얕·지중경사계 단독 라벨',
      '토압계 감지면 누락'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-020': {
    title: '압밀 침하 계측 개념도',
    webp: 'assets/images/technology/IMG-020_압밀-침하-계측-개념도_시간침하간극수압소산.webp',
    alt: '압밀 침하 계측 개념도 - 시간-침하-간극수압 소산 관계',
    caption: '압밀 침하 계측 개념도 — 시간-침하-간극수압 소산 관계',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-020',
    prohibitedErrors: [
      '기준점을 성토 영향권 안에 배치',
      '침하판 상단을 기준점으로 표기',
      '간극수압계가 침하량 직접 측정'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-021': {
    title: '측방유동 계측도',
    webp: 'assets/images/technology/IMG-021_측방유동-계측도_연약층측방변위경사계.webp',
    alt: '측방유동 계측도 - 성토 하부 연약층의 측방변위와 지중경사계',
    caption: '측방유동 계측도 — 성토 하부 연약층의 측방변위와 지중경사계',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-021',
    prohibitedErrors: [
      '연약층 전체 균일 좌우 밀림',
      '침하계로 측방유동 측정',
      '지중경사계 안정층 근입 생략'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-022': {
    title: '구조물 안전계측 전체 개념도',
    webp: 'assets/images/technology/IMG-022_구조물-안전계측-전체-개념도_균열경사진동변위.webp',
    alt: '구조물 안전계측 전체 개념도 - 균열, 경사, 진동, 변위 계측 통합 표현',
    caption: '구조물 안전계측 전체 개념도 — 균열, 경사, 진동, 변위 계측 통합 표현',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-022',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-023': {
    title: '철도 노반 계측 개념도',
    webp: 'assets/images/technology/IMG-023_철도-노반-계측-개념도_침하진동변위계측.webp',
    alt: '철도 노반 계측 개념도 - 철도 노반 침하·진동·변위 계측',
    caption: '철도 노반 계측 개념도 — 철도 노반 침하·진동·변위 계측',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-023',
    prohibitedErrors: [
      '레일 변위와 노반침하 동일 센서',
      '진동 단위와 침하 단위 혼재',
      '철도 계측 단일 로거 흐름도 단순화'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-024': {
    title: '댐 안전관리 계측 체계도',
    webp: 'assets/images/technology/IMG-024_댐-안전관리-계측-체계도_필댐6항목데이터흐름.webp',
    alt: '댐 안전관리 계측 체계도 - 필댐 6항목·침윤선·누수·데이터 흐름',
    caption: '댐 안전관리 계측 체계 — 필댐 6항목·7단계 데이터 흐름 (v4)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-024',
    prohibitedErrors: [
      '침하 그래프 -20mm=경보 -60mm=관리기준 역전 (DAM-01)',
      '침윤선 파선과 피에조 수두 불일치 (DAM-02)',
      '간극수압계 개방 standpipe·전관 수면 (DAM-03)',
      '지하수위계와 동형 관 (EXC-03)',
      '콘크리트 중력식 단면 혼재 (DAM-04)',
      '지하수위선≠해석 침윤선 라벨 (DAM-05)',
      '하단 7단계 데이터 흐름 누락 (DAM-06)',
      '관리기준 항목별 로직 불일치 (DAM-07)',
      '누수계를 제체 내부 박힌 센서처럼 표현',
      '간극수압계가 누수량 직접 측정',
      '침투선을 실측값처럼 단정'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-025': {
    title: '지중경사계 시스템 구성도',
    webp: 'assets/images/technology/IMG-025_지중경사계-시스템-구성도_ProbeCableReadoutCasing.webp',
    alt: '센서형 다단식 지중경사계 시스템 구성도 - IPI·케이싱(4홈)·안정층 Base·자동 데이터로거 체인',
    caption: '센서형 다단식 지중경사계 시스템 — IPI·케이싱(4홈)·안정층 Base·자동 데이터로거 체인',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-025',
    prohibitedErrors: [
      '지중경사계를 침하계처럼 표현',
      '「지중경사계」단독 Figure 라벨 — 센서형 다단식 전칭 필수',
      '케이싱 4홈·프로브 휠 누락',
      '안정층 근입 없이 중단',
      '수평변위를 수직 침하로 표현',
      '수동 probe·리드아웃을 hero로 표현 (AUTO-01)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-026': {
    title: '지중경사계 케이싱 단면도',
    webp: 'assets/images/technology/IMG-026_지중경사계-케이싱-단면도_GuideGroove4방향ProbeWheel.webp',
    alt: '센서형 다단식 지중경사계 케이싱 단면도 - Guide groove 4방향과 Probe wheel 구조',
    caption: '센서형 다단식 지중경사계 케이싱 단면도 — Guide groove 4방향과 Probe wheel 구조',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-026',
    prohibitedErrors: [
      'A축/B축을 화면 좌표처럼 표현',
      '굴착·활동방향과 무관한 축 방향',
      '축 방향 설정 오류 경고 누락'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-027': {
    title: '지중경사계 설치 단면도',
    webp: 'assets/images/technology/IMG-027_지중경사계-설치-단면도_보링그라우트안정층활동면.webp',
    alt: '센서형 다단식 지중경사계 설치 단면도 - 보링공, 그라우트, 안정층 근입, 활동면 표시',
    caption: '센서형 다단식 지중경사계 설치 단면 — 보링공, 그라우트, 케이싱, 안정층 근입, 활동면(변위 집중 심도)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-027',
    prohibitedErrors: [
      'P1: 수평변위← — 활동면·슬라이딩→ 역학 모순',
      'P2: Base 얕은 관입 — 절대 고정단 1~3 m+ (권장 3~5 m+) 미달',
      '활동면·변위 집중 심도 미표시',
      '안정층 근입 누락',
      '수평변위를 수직 침하로 표현',
      '센서형 다단식 미표현',
      '「지중경사계」단독 Figure 라벨 — 센서형 다단식 전칭 필수'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-028': {
    title: '지중경사계 측정 원리도',
    webp: 'assets/images/technology/IMG-028_지중경사계-측정-원리도_기울기누적변위계산.webp',
    alt: '센서형 다단식 지중경사계 측정 원리도 - 기울기 측정에서 누적변위 계산까지',
    caption: '센서형 다단식 지중경사계 측정 원리도 — 기울기 측정에서 누적변위 계산까지',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-028',
    prohibitedErrors: [
      '초기 프로파일 없이 변위 산정',
      '현재 기울기 θ만으로 곧바로 누적변위',
      '하부 기준점 항상 고정 단정',
      '왕복 측정·누적오차 미표시'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-029': {
    title: '지중경사계 데이터 해석도',
    webp: 'assets/images/technology/IMG-029_지중경사계-데이터-해석도_IncrementalCumulative활동면.webp',
    alt: '센서형 다단식 지중경사계 데이터 해석 - 변위 집중 구간과 활동면 추정 구간',
    caption: '센서형 다단식 지중경사계 데이터 해석도 — 변위 집중·활동면 추정 분리',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-029',
    prohibitedErrors: [
      '최대변위깊이=활동면',
      '단일 IPI 확정'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-030': {
    title: '지하수위계 설치 개념도',
    webp: 'assets/images/technology/IMG-030_지하수위계-설치-개념도_관측공수위센서케이블보호함.webp',
    alt: '지하수위계 설치 개념도 - 관측공, 수위 센서, 케이블, 보호함 표현',
    caption: '지하수위계 설치 — well cap·screen·filter pack·bentonite seal·개방 G.W.L·submersible logger',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-030',
    prohibitedErrors: [
      '벽체 부착 센서로 표현',
      '토압계·간극수압계와 혼동',
      '수위선 없이 센서만 표시',
      '방수보호함만 표시 (well cap·screen·seal 누락)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-031': {
    title: '간극수압계 설치도',
    webp: 'assets/images/technology/IMG-031_간극수압계-설치도_필터그라우트케이블.webp',
    alt: '간극수압계 설치도 - 토층 내부 필터·그라우트·케이블, 지하수위계와 구분',
    caption: '간극수압계 설치 — 필터·그라우트 차수·junction→로거(≠ 관측공·개방 수면)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-031',
    prohibitedErrors: [
      '지하수위 관측공 전체 개방으로 표현',
      '수위선만 표시하고 필터·차수 누락',
      '벽체 표면 센서로 표현',
      'G.W.L 라벨로 간극수압 오인'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-032': {
    title: '침하판·침하계 설치 개념도',
    webp: 'assets/images/technology/IMG-032_침하판-침하계-설치-개념도_성토하부연장봉보호관.webp',
    alt: '침하판·침하계 설치 개념도 - 성토 하부 침하판과 연장봉, 보호관 표시',
    caption: '침하판·침하계 설치 개념도 — 성토 하부 침하판과 연장봉, 보호관 표시',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-032',
    prohibitedErrors: [
      '연장봉 상단을 기준점으로 표기',
      '측정점·안정 기준점 미분리'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-033': {
    title: '층별침하계 개념도',
    webp: 'assets/images/technology/IMG-033_층별침하계-개념도_자석링기준관층별침하.webp',
    alt: '층별침하계 개념도 - 자석 링, 기준관, 층별 침하 측정 원리',
    caption: '층별침하계 개념도 — 자석 링, 기준관, 층별 침하 측정 원리',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-033',
    prohibitedErrors: [
      '자석링을 로거 직결 전기센서처럼 표현',
      '기준관이 지반과 함께 침하',
      '층별침하 막대그래프만·기준 위치 생략'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-034': {
    title: '토압계 설치 개념도',
    webp: 'assets/images/technology/IMG-034_토압계-설치-개념도_흙막이배면성토부.webp',
    alt: '토압계 설치 개념도 - 흙막이 배면 또는 성토부 토압계 설치',
    caption: '토압계 설치 — 벽체 배면 감지면과 토압 작용 방향(배면 지반→벽체)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-034',
    prohibitedErrors: [
      '감지면 방향 없는 원형 아이콘',
      '관측공 내부 설치',
      '굴착측 앞면 임의 부착',
      '성토 하중=토압계 측정값',
      'q·σh 미분리'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-035': {
    title: '하중계 설치 개념도',
    webp: 'assets/images/technology/IMG-035_하중계-설치-개념도_버팀보앵커하중전달.webp',
    alt: '하중계 설치 개념도 - 버팀보/앵커 하중계의 하중 전달 구조',
    caption: '하중계 설치 — 버팀보 띠장 접합부(끝단) 축방향·어스앵커 두부 인장',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-035',
    prohibitedErrors: [
      '버팀보 정중앙 하중계',
      '축방향과 무관한 설치',
      '옆면 장식처럼 배치',
      'strut LC와 anchor LC 혼동'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-036': {
    title: '변형률계 설치 개념도',
    webp: 'assets/images/technology/IMG-036_변형률계-설치-개념도_철근강재표면부착.webp',
    alt: '변형률계 설치 개념도 - 철근 또는 강재 표면 부착형 변형률계',
    caption: '변형률계 설치 개념도 — 철근 또는 강재 표면 부착형 변형률계',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-036',
    prohibitedErrors: [
      '변형률 수치=구조 안전판정',
      '게이지 방향 미표시',
      '온도보정·E·중립축 생략'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-037': {
    title: '균열계 설치 개념도',
    webp: 'assets/images/technology/IMG-037_균열계-설치-개념도_균열양측앵커변위측정.webp',
    alt: '균열계 설치 개념도 - 균열 양측 앵커와 변위 측정 방향 표시',
    caption: '균열계 설치 개념도 — 균열 양측 앵커와 변위 측정 방향 표시',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-037',
    prohibitedErrors: [
      '균열과 평행 설치',
      '균열 없이 센서만 부착',
      '균열계로 3D 거동 전체 측정',
      '균열폭 변화=균열 길이 증가 동일 표기',
      '전단·단차·회전을 균열계로 대체'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-038': {
    title: '구조물 경사계 설치도',
    webp: 'assets/images/technology/IMG-038_구조물-경사계-설치도_벽체교각표면.webp',
    alt: '구조물 경사계 설치도 - 벽체 또는 교각 표면 경사계 설치',
    caption: '구조물 경사계 설치도 — 벽체 또는 교각 표면 경사계 설치',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-038',
    prohibitedErrors: [
      '지중경사계와 혼동',
      '지반 내부 센서로 표현',
      '유연 브라켓 위 센서 = 구조물 전체 경사',
      '브라켓 처짐을 기준면으로 표현',
      '1점 경사로 전체 기울기 단정'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-039': {
    title: '신축계 설치 개념도',
    webp: 'assets/images/technology/IMG-039_신축계-설치-개념도_이음부조인트상대변위.webp',
    alt: '신축계 설치 개념도 - 이음부, 조인트, 상대변위 측정',
    caption: '신축계 설치 개념도 — 이음부, 조인트, 상대변위 측정',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-039',
    prohibitedErrors: [
      '신축계=신축이음계 동일 센서',
      'LVDT·균열계·신축계 동일 범례',
      '신축계로 수평·수직 전방위 동시 측정'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-040': {
    title: '변위계 설치 개념도',
    webp: 'assets/images/technology/IMG-040_변위계-설치-개념도_기준점대상점변위측정.webp',
    alt: '변위계 설치 개념도 - 기준점과 대상점 사이 변위 측정',
    caption: '변위계 설치 개념도 — 기준점과 대상점 사이 변위 측정',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-040',
    prohibitedErrors: [
      '기준점 항상 완전 고정 가정',
      '측정축 무관 부착',
      'stroke·브라켓 유격 미표시'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-041': {
    title: '진동계 설치 개념도',
    webp: 'assets/images/technology/IMG-041_진동계-설치-개념도_구조물지반3축방향.webp',
    alt: '진동계 설치 개념도 - 구조물 또는 지반 진동 센서와 3축 방향',
    caption: '진동계 설치 개념도 — 구조물 또는 지반 진동 센서와 3축 방향',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-041',
    prohibitedErrors: [
      '가속도(m/s² 또는 mm/s) 혼합 표기'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-042': {
    title: '자동광파기 계측 개념도',
    webp: 'assets/images/technology/IMG-042_자동광파기-계측-개념도_TotalStation프리즘좌표변위.webp',
    alt: '자동광파기 계측 개념도 - Total station, prism, 좌표 변위 측정',
    caption: '자동광파기 계측 — Total Station, 기준점·시준선, 프리즘, 좌표 변위 벡터(ΔX·ΔY)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-042',
    prohibitedErrors: [
      'CCTV·카메라 표현',
      '프리즘·시준선 없음',
      '레이저스캐너 혼동',
      '기준 프리즘 없이 대상만',
      'ATS 한 대가 절대변위 자동 확정',
      '후시점·기상보정 누락'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-043': {
    title: 'GNSS 변위 계측 개념도',
    webp: 'assets/images/technology/IMG-043_GNSS-변위-계측-개념도_기준국이동국서버연결.webp',
    alt: 'GNSS 변위 계측 개념도 - 기준국·이동국·GNSS 안테나·RTK·무선·중앙 서버·3D 변위 (book/GNSS.pdf)',
    caption: 'GNSS 변위 계측 개념도 — 기준국·이동국·RTK·중앙 서버·3D 변위',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-043',
    prohibitedErrors: [
      '기준국을 변형 구간에 배치',
      '이동국·기준국 역할 역전',
      '광파기·프리즘·레이저스캐너 표현',
      '기준국 없이 단일 안테나만',
      'book/GNSS.pdf 제조사 로고·상표 복사',
      'GNSS 기준국이 이동국 직접 시준',
      '광파 시준선 유사 점선'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-044': {
    title: '기상계측기 구성도',
    webp: 'assets/images/technology/IMG-044_기상계측기-구성도_강우량풍향온습도기압.webp',
    alt: '기상계측기 구성도 - 강우량, 풍향풍속, 온습도, 기압 센서',
    caption: '기상계측기 구성도 — 강우량, 풍향풍속, 온습도, 기압 센서',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-044',
    prohibitedErrors: [
      '장애물 무시 임의 설치',
      '기상-변위 상관=인과',
      '설치 높이·이격 미표시'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-045': {
    title: '데이터로거 구성도',
    webp: 'assets/images/technology/IMG-045_데이터로거-구성도_센서입력전원통신저장.webp',
    alt: '데이터로거 구성도 - 센서 입력, 전원, 통신, 저장 장치 구성',
    caption: '데이터로거 구성도 — 산업용 함체·센서입력·전원·통신·저장',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-045',
    prohibitedErrors: [
      '내부 CPU·저장·통신 블록 다이어그램만',
      '정사각 접속함·DATA LOGGER 세로 박스',
      '브랜드·CR1000X 모델명 인쇄',
      '흙막이 단면 주 화면',
      '모든 센서 동일 아날로그 입력',
      '로거가 센서 종류 자동 처리',
      '신호 형식·여자전원 미구분'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-046': {
    title: 'IoT 게이트웨이 구성도',
    webp: 'assets/images/technology/IMG-046_IoT-게이트웨이-구성도_현장센서서버통신중계.webp',
    alt: 'IoT 게이트웨이 구성도 - 현장 센서와 서버 사이 통신 중계',
    caption: 'IoT 게이트웨이 구성도 — 현장 센서와 서버 사이 통신 중계',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-046',
    prohibitedErrors: [
      'GW=로거 동일',
      'GW 관리기준 판정',
      '로컬저장 vs GW버퍼 미구분'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-047': {
    title: '태양광 전원 시스템 구성도',
    webp: 'assets/images/technology/IMG-047_태양광-전원-시스템-구성도_패널컨트롤러배터리로거.webp',
    alt: '태양광 전원 시스템 구성도 - 태양광 전원 — 부하·자율운전일·LVD·SPD·접지 (Phase AD)',
    caption: '태양광 전원 시스템 구성도 — 부하·충전·배터리·보호·로거',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-047',
    prohibitedErrors: [
      '무정전 보장 암시',
      '부하 산정 없이 12V만'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-048': {
    title: 'LTE M2M 통신 구성도',
    webp: 'assets/images/technology/IMG-048_LTE-M2M-통신-구성도_센서로거모뎀서버웹모바일.webp',
    alt: 'LTE M2M 통신 구성도 - LTE M2M — 로컬 버퍼·재전송·APN·ACK (Phase AD)',
    caption: 'LTE M2M 통신 구성도 — 로거·모뎀·망·서버·클라이언트',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-048',
    prohibitedErrors: [
      'LTE 모뎀·통신사 브랜드 로고',
      '센서·로거 생략',
      '클라우드 UI 스크린샷 복사',
      '센서→로거→LTE→서버 직렬만',
      '로컬 저장·재전송 없음',
      'APN·VPN·ACK·방화벽 누락',
      'LTE 모뎀이 경보 판정'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-049': {
    title: '변위 그래프 예시',
    webp: 'assets/images/technology/IMG-049_변위-그래프-예시_관리기준선실시간추세.webp',
    alt: '변위 그래프 예시 - 변위 시계열 — 방향·상대변위·속도·현장별 기준 (Phase AD)',
    caption: '변위 그래프 예시 — 관리기준선과 실시간 변위 추세 그래프',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-049',
    prohibitedErrors: [
      '단일 ±기준선 보편화',
      '단일계=전체 안정',
      '기준점·속도 누락'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-050': {
    title: '침하 그래프 예시',
    webp: 'assets/images/technology/IMG-050_침하-그래프-예시_시간침하곡선예측선.webp',
    alt: '침하 그래프 예시 - 침하-시간 계측 및 예측 — 해석법·성토단계 (Phase AD)',
    caption: '침하-시간 계측 및 예측 개념도 — 측정·해석·성토단계',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-050',
    prohibitedErrors: [
      '선형외삽 예측',
      '침하판=기준점',
      '보편 관리기준'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-051': {
    title: '간극수압 소산 그래프',
    webp: 'assets/images/technology/IMG-051_간극수압-소산-그래프_성토단계상승소산.webp',
    alt: '간극수압 소산 그래프 - 간극수압 Δu·초기 정수압·심도별 소산 (Phase AD)',
    caption: '간극수압 소산 그래프 — 성토 단계와 간극수압 상승/소산',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-051',
    prohibitedErrors: [
      '단계별 동일곡선',
      'G.W.L=piezo'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-052': {
    title: '하중 변화 그래프',
    webp: 'assets/images/technology/IMG-052_하중-변화-그래프_버팀보하중경보기준선.webp',
    alt: '하중 변화 그래프 - 버팀보 하중 — 단계별 설계축력·프리로드 (Phase AD)',
    caption: '하중 변화 그래프 — 버팀보 하중 변화와 경보 기준선',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-052',
    prohibitedErrors: [
      '전단계 동일 기준선',
      '하중감소=안전'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-053': {
    title: '진동 계측 그래프',
    webp: 'assets/images/technology/IMG-053_진동-계측-그래프_PPV기준선표현.webp',
    alt: '진동 계측 그래프 - 진동 PPV — 3축·주파수·축 통일 (Phase AD)',
    caption: '진동 계측 그래프 — 진동속도 PPV와 기준선 표현',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-053',
    prohibitedErrors: [
      '축 혼동',
      '보편 PPV 기준'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-054': {
    title: '경보 단계 프로세스',
    webp: 'assets/images/technology/IMG-054_경보-단계-프로세스_정상주의경고위험조치.webp',
    alt: '경보 단계 프로세스 - 경보 프로세스 — QC·결측·현장확인·해제 (Phase AD)',
    caption: '경보 단계 프로세스 — 정상-주의-경고-위험-조치 흐름',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-054',
    prohibitedErrors: [
      '선형 4단계만',
      '초과=위험 단정'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-055': {
    title: '모바일 경보 알림 화면',
    webp: 'assets/images/technology/IMG-055_모바일-경보-알림-화면_휴대폰경보표현.webp',
    alt: '모바일 경보 알림 화면 - 모바일 경보 — 상태·지속·추세·조치 로그 (Phase AD)',
    caption: '모바일 경보 알림 화면 — 실제 휴대폰 알림창 형태의 경보 표현',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-055',
    prohibitedErrors: [
      '색상만 경보',
      '실사 휴대폰'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-056': {
    title: '웹 대시보드 구성도',
    webp: 'assets/images/technology/IMG-056_웹-대시보드-구성도_지도센서목록그래프이벤트로그.webp',
    alt: '웹 대시보드 구성도 - 웹 대시보드 — 상태 일관·단위·이벤트 연계 (Phase AD)',
    caption: '웹 대시보드 구성도 — 지도, 센서목록, 그래프, 이벤트 로그',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-057',
    prohibitedErrors: [
      '전 센서 초록',
      '축·단위 없는 그래프'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-057': {
    title: '자동 보고서 생성 흐름도',
    webp: 'assets/images/technology/IMG-057_자동-보고서-생성-흐름도_계측데이터PDF보고서.webp',
    alt: '자동 보고서 생성 흐름도 - 계측 데이터에서 PDF 보고서까지',
    caption: '자동 보고서 생성 흐름도 — 계측 데이터에서 PDF 보고서까지',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-057',
    prohibitedErrors: [
      '설치 체크리스트 혼동',
      '빈 클라우드 박스'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-058': {
    title: '통합 계측 플랫폼 아키텍처',
    webp: 'assets/images/technology/IMG-058_통합-계측-플랫폼-아키텍처_센서로거서버DB웹모바일.webp',
    alt: '통합 계측 플랫폼 아키텍처 - 센서-로거-서버-DB-웹-모바일 구조',
    caption: '원격계측 플랫폼 — 센서·데이터로거·통신·서버·DB·웹·모바일 계층 구조',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-058',
    prohibitedErrors: [
      '내부 CPU 블록만 표현',
      'CR1000X 실사·브랜드',
      '흙막이·터널 단면 주 화면',
      '뇌·홀로그램·SF UI'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-059': {
    title: '관리기준 설정 개념도',
    webp: 'assets/images/technology/IMG-059_관리기준-설정-개념도_센서별기준치경보조건.webp',
    alt: '관리기준 설정 개념도 - 센서별 기준치와 경보 조건 설정',
    caption: '관리기준 설정 개념도 — 센서별 기준치와 경보 조건 설정',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-059',
    prohibitedErrors: [
      '모든 센서 동일 경보',
      '출처 없는 수치',
      '자동 삭제'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-060': {
    title: '데이터 품질관리 흐름도',
    webp: 'assets/images/technology/IMG-060_데이터-품질관리-흐름도_수집검증보정분석보고.webp',
    alt: '데이터 품질관리 흐름도 - 수집-검증-보정-분석-보고 절차',
    caption: '데이터 품질관리 흐름도 — 수집-검증-보정-분석-보고 절차',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-060',
    prohibitedErrors: [
      '이상치 자동 삭제',
      '원본 미보존'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-061': {
    title: '터널 천단침하 계측 개념도',
    webp: 'assets/images/technology/IMG-061_천단침하계-외부-수준점-계측-개념도.webp',
    alt: '터널 천단침하 계측 개념도 - 터널 내부 천단 측점·프리즘·ATS 측량 — 내공변위와 구분',
    caption: '터널 천단침하 계측 개념도 — 천단 측점·자동광파기·δ 침하',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-061',
    prohibitedErrors: [
      '외부 수준점–천단 와이어·케이블 직결 (TUN-CROWN-01)',
      '천단침하계(앵커) 라이닝·지반 관통 (TUN-CROWN-02)',
      '지중침하계·층별침하계 표현 (TUN-CROWN-03)',
      '데이터 로거 필수 구성 (TUN-CROWN-04)',
      '상부 지반 관통 수직 침하계 (TUN-CROWN-05)',
      '축방향 다수 지점 센서열 (TUN-CROWN-06)',
      'BM을 와이어 고정 상부로 표현 (TUN-CROWN-07)',
      '천단·내공·지표·지중 혼동 (TUN-CROWN-08)',
      '데이터 흐름도 (TUN-CROWN-11)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-062': {
    title: '지하수위·간극수압 계측도',
    webp: 'assets/images/technology/IMG-062_지하수위-간극수압-계측도.webp',
    alt: '지하수위·간극수압 계측도 - 배면 지반 관측공·천공 내 수위계·간극수압계 배치',
    caption: '지하수위·간극수압 계측도 — ① 관측공 개방 수면 vs ② 밀폐 필터 간극수압(이형)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-062',
    prohibitedErrors: [
      '지하수위계를 벽체 표면에 부착',
      '②③ 동형 관 표현 (관측공=간극수압 혼동)',
      '수위선 없이 센서만 표시',
      '굴착 바닥에만 센서 표시'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-063': {
    title: '막장전방 선행변위 계측 개념도',
    webp: 'assets/images/technology/IMG-063_막장전방-선행변위-계측-개념도_막장전방지반.webp',
    alt: '막장전방 선행변위 계측 개념도 - 막장 전방 지반 선행변위계 배치·굴진 방향·막장거리',
    caption: '막장전방 선행변위 계측 — 막장 앞 지반 선행변위계·굴진 방향·막장거리',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-063',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-064': {
    title: '항만·호안 계측 전체 개념도',
    webp: 'assets/images/technology/IMG-064_항만-호안-계측-전체-개념도_케이슨옹벽주변지반.webp',
    alt: '항만·호안 계측 전체 개념도 - [좌]육측|케이슨·안벽|[우]해측 횡단·구조물·주변지반·조위 계측 개요',
    caption: '항만·호안 계측 전체 개념도 — 케이슨·안벽 구조물과 육측·해측 지반·조위·지하수 계측',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-064',
    prohibitedErrors: [
      '케이슨·옹벽·주변지반 구분 누락',
      '조위선·지하수위선 혼동',
      '지하수위계를 벽체 부착으로 표현',
      '간극수압계를 관측공으로 표현'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-065': {
    title: '현장 계측 전원 통합 구성도',
    webp: 'assets/images/technology/IMG-065_현장-계측-전원-통합-구성도_태양광풍력AC배터리.webp',
    alt: '현장 계측 전원 통합 구성도 - 태양광·풍력·AC·AVR·배터리 통합',
    caption: '현장 계측 전원 통합 구성도 — 무인 구간·AC 구간·공용 배터리',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-065',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-066': {
    title: '상시 전원 AC 인입',
    webp: 'assets/images/technology/IMG-066_상시-전원-AC-인입_배전반차단기정류.webp',
    alt: '상시 전원 AC 인입 - 배전반·차단기·AC-DC 정류',
    caption: '상시 전원 AC 인입 — 배전반·Surge·AC-DC·계측 함체',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-066',
    prohibitedErrors: [
      '빈 박스·PPT 와이어프레임',
      '뇌·실사 풍경'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-067': {
    title: 'AVR 자동전압조정기',
    webp: 'assets/images/technology/IMG-067_AVR-자동전압조정기_입력출력안정화.webp',
    alt: 'AVR 자동전압조정기 - 불안정 AC 입력 전압 안정화',
    caption: 'AVR 자동전압조정기 — 입력 변동·220V 안정 출력',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-067',
    prohibitedErrors: [
      '빈 박스·PPT 와이어프레임',
      '뇌·실사 풍경'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-068': {
    title: '풍력 하이브리드 전원',
    webp: 'assets/images/technology/IMG-068_풍력-하이브리드-전원_태양광풍력배터리.webp',
    alt: '풍력 하이브리드 전원 - 태양광·풍력·공용 배터리',
    caption: '풍력 하이브리드 전원 — 태양광 보완·공용 배터리',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-068',
    prohibitedErrors: [
      '빈 박스·PPT 와이어프레임',
      '뇌·실사 풍경'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-069': {
    title: '배터리·축전 시스템',
    webp: 'assets/images/technology/IMG-069_배터리-축전-시스템_용량종류모니터링.webp',
    alt: '배터리·축전 시스템 - 용량·종류·DoD·모니터링',
    caption: '배터리·축전 시스템 — AGM·LiFePO₄·용량 산정',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-069',
    prohibitedErrors: [
      '빈 박스·PPT 와이어프레임',
      '뇌·실사 풍경'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-070': {
    title: '수동 계측 개념도',
    webp: 'assets/images/technology/IMG-070_수동-계측-개념도_현장방문리드아웃기록.webp',
    alt: '수동 계측 개념도 - 현장 방문·리드아웃·현장 기록',
    caption: '수동 계측 — 현장 방문·휴대 장비·측정일지',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-070',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-071': {
    title: '자동 계측 개념도',
    webp: 'assets/images/technology/IMG-071_자동-계측-개념도_로거현장저장주기.webp',
    alt: '자동 계측 개념도 - 데이터로거·현장 저장·수집 주기',
    caption: '자동 계측 — 로거·주기 수집·현장 저장',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-071',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-072': {
    title: '원격 자동계측 개념도',
    webp: 'assets/images/technology/IMG-072_원격-자동계측-개념도_현장통신서버모니터링.webp',
    alt: '원격 자동계측 개념도 - 현장·통신·서버·원격 모니터링',
    caption: '원격 자동계측 — LTE·서버·웹·경보',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-072',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-073': {
    title: '스마트 계측 개념도',
    webp: 'assets/images/technology/IMG-073_스마트-계측-개념도_플랫폼경보보고로그.webp',
    alt: '스마트 계측 개념도 - 플랫폼·경보·보고·이벤트 로그',
    caption: '스마트 계측 — 운영 플랫폼·단계별 경보',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-073',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-074': {
    title: 'AI 계측 개념도',
    webp: 'assets/images/technology/IMG-074_AI-계측-개념도_이상탐지예측HITL.webp',
    alt: 'AI 계측 개념도 - 이상탐지·예측·HITL 보조',
    caption: 'AI 계측 — 분석 엔진·검토·보조 의사결정',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-074',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-075': {
    title: '계측 방식 5단계 계층도',
    webp: 'assets/images/technology/IMG-075_계측-방식-5단계-계층도_수동자동원격스마트AI.webp',
    alt: '계측 방식 5단계 계층도 - 수동·자동·원격·스마트·AI 포함 관계',
    caption: '계측 방식 5단계 — 하위 포함·능력 누적',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-075',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-076': {
    title: '동적 데이터로거 구성도',
    webp: 'assets/images/technology/IMG-076_동적-데이터로거-구성도_모듈형DAQ고속샘플링.webp',
    alt: '동적 데이터로거 구성도 - 모듈형 DAQ·고속 동시 샘플링·IEPE 입력',
    caption: '동적 DAQ — 모듈형 섀시·이더넷 스트리밍·파형 분석',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-076',
    prohibitedErrors: [
      'CR1000X 정적로거 혼동',
      '제조사 모델명'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-077': {
    title: '멀티플렉서(MUX) 구성도',
    webp: 'assets/images/technology/IMG-077_멀티플렉서-구성도_체인센서순차스캔.webp',
    alt: '멀티플렉서(MUX) 구성도 - 체인 센서·순차 스캔·정적 로거 채널 확장',
    caption: 'MUX — 지중경사·VW 체인 → 순차 스캔 → 정적 로거',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-077',
    prohibitedErrors: [
      '동시 측정 표현',
      'VW·진동현식 라벨'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-078': {
    title: '록볼트 축력 계측 개념도',
    webp: 'assets/images/technology/IMG-078_록볼트-축력-계측-개념도_축력계변형률계.webp',
    alt: '록볼트 축력 계측 개념도 - 록볼트 축력계·변형률계 천단·어깨 배치',
    caption: '록볼트 축력 — LC·굴착 단계별 추이',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-078',
    prohibitedErrors: [
      '두부 하중=P 전체 록볼트 축력',
      '축력분포·변형률계 미구분'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-079': {
    title: '숏크리트 응력·변형 계측 개념도',
    webp: 'assets/images/technology/IMG-079_숏크리트-응력-변형-계측-개념도_변형률계매립.webp',
    alt: '숏크리트 응력·변형 계측 개념도 - 변형률계 매립·라이닝 부담',
    caption: '숏크리트 응력·변형 — 매립 SG·응력계 (v3 AI)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-079',
    prohibitedErrors: [
      '숏크리트 응력계로 터널 전체 안정성 평가',
      '숏크리트 응력계=토압계',
      '지반압 화살표와 센서 1:1 연결'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-080': {
    title: '강지보 응력 계측 개념도',
    webp: 'assets/images/technology/IMG-080_강지보-응력-계측-개념도_스틸세트변형률계.webp',
    alt: '강지보 응력 계측 개념도 - 스틸 세트·변형률계',
    caption: '강지보 — 스틸 세트 변형률',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-080',
    prohibitedErrors: [
      '플랜지 일부 변형률만으로 전체 응력 대표',
      '내외측·다점 계측 미표시'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-081': {
    title: '기둥 축소량 계측 개념도',
    webp: 'assets/images/technology/IMG-081_기둥-축소량-계측-개념도_수직변형률계.webp',
    alt: '기둥 축소량 계측 개념도 - 수직 변형률계·층별 축소',
    caption: '기둥 축소량 — 층별 변형률',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-081',
    prohibitedErrors: [
      '수직 로드 하나가 모든 층 축소 직접 측정',
      'RF층을 절대 기준점',
      '크리프·건조수축·탄성축소 단순화'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-082': {
    title: '건축 응력·변형률 계측 개념도',
    webp: 'assets/images/technology/IMG-082_건축-응력변형률-계측-개념도_중대부재하중계.webp',
    alt: '건축 응력·변형률 계측 개념도 - 중대 부재·하중계',
    caption: '건축 응력·변형률 — KCS 3.9',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-082',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-083': {
    title: '댐 변형률 계측 개념도',
    webp: 'assets/images/technology/IMG-083_댐-변형률-계측-개념도_제체매립SG.webp',
    alt: '댐 변형률 계측 개념도 - 제체 매립 변형률계',
    caption: '댐 제체 — 변형률 모니터링',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-083',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-084': {
    title: '항만구조물 변위 계측 개념도',
    webp: 'assets/images/technology/IMG-084_항만구조물-변위-계측-개념도_케이슨안벽변위계.webp',
    alt: '항만구조물 변위 계측 개념도 - 케이슨·안벽 변위계',
    caption: '항만구조물 — 변위·반력',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-084',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-086': {
    title: '교량 진동 계측 개념도',
    webp: 'assets/images/technology/IMG-086_교량-진동-계측-개념도_가속도계통행응답.webp',
    alt: '교량 진동 계측 개념도 - 가속도계·통행 응답',
    caption: '교량 진동 — ACC 배치',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-086',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-087': {
    title: '구조물 지진 계측 개념도',
    webp: 'assets/images/technology/IMG-087_구조물-지진-계측-개념도_강진동응답스펙트럼.webp',
    alt: '구조물 지진 계측 개념도 - 강진동·응답 스펙트럼',
    caption: '지진·지동 — 구조 응답',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-087',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-088': {
    title: '구조물 온도 계측 개념도',
    webp: 'assets/images/technology/IMG-088_구조물-온도-계측-개념도_온도계수화열계절.webp',
    alt: '구조물 온도 계측 개념도 - 온도계·수화열·계절 변동',
    caption: '구조물 온도 — 계절·수화열',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-088',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-089': {
    title: '사면 지표경사 계측 개념도',
    webp: 'assets/images/technology/IMG-089_사면-지표경사-계측-개념도_지표경사계pad콘크리트.webp',
    alt: '사면 지표경사 계측 개념도 - 지표 pad tiltmeter — θ · ≠ 지중경사계',
    caption: '사면 지표경사 — pad tiltmeter · θ',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-089',
    prohibitedErrors: [
      '지중경사계 보링 casing',
      '풍경화·숲',
      '구조물경사계(IMG-038)',
      '지표경사계 pad·θ 미표기 (SLO-TILT-01)',
      'pad 없이 지중 매설',
      '흙막이·교량 풍경 맥락'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-090': {
    title: '사면 구조물 변위 계측 개념도',
    webp: 'assets/images/technology/IMG-090_사면-구조물-변위-계측-개념도_배면사면와이어식변위계.webp',
    alt: '사면 구조물 변위 계측 - 배면 사면 와이어식 변위계와 옹벽 프리즘 측점',
    caption: '사면 구조물 변위 계측 — 배면 사면 와이어식 변위계 · 옹벽 프리즘 · ΔX/ΔY',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-090',
    prohibitedErrors: [
      '옹벽 전면·벽체에 와이어식 변위계 부착 (SLO-WIRE-01)',
      'ATS만 hero — 와이어식 변위계 없음 (DISP-ATS-01)',
      'ATS 옹벽·사면 꼭대기 부착',
      '흙막이 굴착·교량 풍경 맥락'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-091': {
    title: '다점지중변위계 (MPBX) 설치 개념도',
    webp: 'assets/images/technology/IMG-091_다점지중변위계-MPBX-설치-개념도_보링다점앵커.webp',
    alt: '다점지중변위계 (MPBX) 설치 개념도 - 보링 내 다점 앵커·강봉 상대변위 — ≠ inclinometer',
    caption: '다점지중변위계 — MPBX · 다점 강봉·앵커 cutaway',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-091',
    prohibitedErrors: [
      '지중경사계 혼동',
      '수평변위 화살표만',
      '신축계(039) 교량 이음부 (MPX-02)',
      '단일 강봉만 — 다점 앵커 없음 (MPX-03)',
      '보링 GL well cap 누락 (P0-2)',
      '4홈 casing·프로브 휠 (MPX-01)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-092': {
    title: '말뚝 축력·변형률 지중 단면도',
    webp: 'assets/images/technology/IMG-092_말뚝-축력-변형률-지중-단면도_CIP철근망변형률계.webp',
    alt: '말뚝 축력·변형률 지중 단면도 - CIP·PHC 말뚝 cage sister-bar · 깊이별 축하중 — ≠ 지상 기둥',
    caption: '말뚝 축력 — 지층 관통 단면·rebar cage·변형률계',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-092',
    prohibitedErrors: [
      '지상 기둥만',
      '교량 pier group(IMG-013)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-093': {
    title: '환경 소음·분진 경계 계측주',
    webp: 'assets/images/technology/IMG-093_환경-소음-분진-경계-계측주_펜스소음PM로거.webp',
    alt: '환경 소음·분진 경계 계측주 - 펜스·민가 레이아웃 · 소음계+PM 일체형 주 — ≠ 대기 그래프',
    caption: '환경 계측 — 경계 펜스·소음·분진·데이터로거',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-093',
    prohibitedErrors: [
      '대기 그래프만',
      '풍경화'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-096': {
    title: '가시설 주변지반 계측 설치 대표 단면도',
    webp: 'assets/images/technology/IMG-096_주변지반-계측-설치-대표-단면도_굴착영향권복합.webp',
    alt: '주변지반 계측 설치 대표 단면도 - 굴착 영향권, 센서형 다단식 지중경사계·침하·간극수압·지하수위',
    caption: '가시설 주변지반 — IPI·침하핀·간극수압·지하수위 4종 · H=굴착깊이 (v4)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-096',
    prohibitedErrors: [
      '잠재 슬립면·활동면 원호 (MIX-01)',
      '옹벽형 영구 구조·캡 (MIX-01)',
      'H·2H 미정의 (DIM-01)',
      '② 「지표침하계」라벨 — 측점/핀만 (SETTLE-01)',
      '② 로거 직결 케이블 (측량·ATS 대상)',
      '지중경사계·지하수위·간극수압 벽체/CIP 내부 매설 (SOE-INST-01)',
      '간극수압계 = 지하수위 관측공 동형',
      '수평변위 ← (P1 역방향)',
      '로거가 계측 배치보다 강조 (G-15)',
      '옹벽·옹벽 기초·옹벽 배면 토압 (SOE-SURR-01)',
      'Sand Mat·침하판 중심 성토부 연상 (MIX-019)',
      '데이터 흐름도·서버·모바일·알람 UI',
      '굴착측과 배면 G.W.L 동일 연속 표시',
      '옹벽·옹벽 기초·옹벽 토압',
      'Sand Mat·침하판 중심(019 혼동)',
      '지표침하핀에 지표침하계 라벨',
      '잠재 슬립면 원호'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'cad'
  },
  'IMG-097': {
    title: '터널 발파진동·영향권 계측 개념도',
    webp: 'assets/images/technology/IMG-097_터널-발파진동-영향권-계측-개념도_PPV측점배치.webp',
    alt: '터널 발파진동·영향권 계측 개념도 - PPV·가속도계 측점·영향권',
    caption: '발파진동·영향권 — PPV·민감 구역 진동 모니터링',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-097',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-098': {
    title: '항만 호안 조위·지하수 계측 개념도',
    webp: 'assets/images/technology/IMG-098_항만-호안-조위지하수-계측-개념도_외해사석매립지하수위.webp',
    alt: '항만 호안 조위·지하수 계측 개념도 - 외해·사석호안·배면 매립 조위·지하수·간극수압 연동',
    caption: '항만 호안 조위·지하수 — H.W.L/L.W.L·stilling well·screen 관측공·tidal lag 침윤선',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-098',
    prohibitedErrors: [
      'fields/harbor/tide-groundwater hero에 IMG-030(육상) 사용 (HAR-01)',
      '해수면·H.W.L/L.W.L·조위계 없음 (HAR-02)',
      '수평 G.W.L — tidal lag 곡선 아님 (HAR-03)',
      '관측공 불통 관 — screen·filter pack 없음 (HAR-04)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-099': {
    title: '건축 구조물 처짐 계측 개념도',
    webp: 'assets/images/technology/IMG-099_건축-구조물-처짐-계측-개념도_RC골조LVDT처짐그래프.webp',
    alt: '건축 구조물 처짐 계측 개념도 - RC 보·슬래브 LVDT 처짐 계측과 시간-처짐 그래프(L/250·L/360)',
    caption: '건축 구조물 처짐 — RC 보·슬래브·LVDT·처짐량(δ) 그래프·설계 허용치',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-099',
    prohibitedErrors: [
      'fields/building/deflection hero에 IMG-050·032·033(침하) 사용 (DEF-01)',
      '성토체·연약지반 단면 (DEF-02)',
      '침하계·침하판 — LVDT·처짐계 아님 (DEF-03)',
      'Y축 침하량·예측 침하·임의 -50mm (DEF-04)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-100': {
    title: '건축공사 계측 전체 개념도',
    webp: 'assets/images/technology/IMG-100_건축공사-계측-전체-개념도_KCS39처짐축소균열.webp',
    alt: '건축공사 계측 전체 개념도 - KCS 3.9 처짐 축소 균열',
    caption: '건축공사 계측 전체 개념도 — LVDT·변형률·균열·경사·하중 (KCS 3.9)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-100',
    prohibitedErrors: [
      'fields/building hero에 IMG-022 사용 (BLD-H-01)',
      '침하계·성토 Figure — 건축 hero 금지'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-101': {
    title: '건축공사 주변건물 계측 개념도',
    webp: 'assets/images/technology/IMG-101_건축공사-주변건물-계측-개념도_신축인접균열경사.webp',
    alt: '건축공사 주변건물 계측 - 신축 현장 인접 건물 균열 경사',
    caption: '건축공사 주변건물 계측 — 균열·경사·와이어식 변위(주)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-101',
    prohibitedErrors: [
      'fields/building/adjacent-building hero에 IMG-005 사용 (BLD-ADJ-01)',
      '굴착 흙막이·버팀보 주 배경'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-094': {
    title: '상시 계측 모드 흐름도',
    webp: 'assets/images/technology/IMG-094_상시-계측-모드-흐름도_등간격트리거stabletrend.webp',
    alt: '상시 계측 모드 흐름도 - 등간격 트리거 · stable trend · 로거→클라우드 — ≠ 시계만',
    caption: '상시 계측 — Normal/Routine Monitoring Mode',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-094',
    prohibitedErrors: [
      '시계 아이콘만',
      '뇌·홀로그램'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-095': {
    title: '실시간·이벤트 계측 모드 토폴로지',
    webp: 'assets/images/technology/IMG-095_실시간-이벤트-계측-모드-토폴로지_고속샘플링impulse.webp',
    alt: '실시간·이벤트 계측 모드 토폴로지 - Trigger Event · 고속 샘플링 · impulse 파형 — ≠ 번개 CG',
    caption: '이벤트 계측 — High-Speed Real-time Mode',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-095',
    prohibitedErrors: [
      '번개 CG',
      '뇌·SF UI'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-102': {
    title: '경보·알림 상태 제어 흐름도',
    webp: 'assets/images/technology/IMG-102_경보-알림-상태-제어-흐름도_threshold경광SMS.webp',
    alt: '경보·알림 상태 제어 흐름도 - 3단계 threshold · Action 돌파 → 경광·SMS — ≠ SF UI',
    caption: '경보 상태 — Caution/Warning/Action → 알림',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-102',
    prohibitedErrors: [
      'SF 경고 팝업',
      '뇌·네온',
      'IMG-054 only without threshold'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-103': {
    title: '교량 상부구조 GNSS 처짐 계측도',
    webp: 'assets/images/technology/IMG-103_교량-상부구조-처짐-계측도_거더처짐계δ.webp',
    alt: '교량 상부구조 GNSS 처짐 계측도 - 경간 상부 이동국 수직변위 ΔZ',
    caption: '교량 GNSS 처짐 — 경간 상부 ΔZ·처짐량 δ (v3, 와이어식 hero 아님)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-103',
    prohibitedErrors: [
      '침하판·지표침하계 hero',
      '성토 단면',
      'Y축 침하량',
      '하부 와이어식 처짐계 hero (DEF-GNSS-04)',
      '교각 측면/중간 GNSS (DEF-GNSS-05)',
      '와이어+GNSS 동시 주계측 (DEF-GNSS-06)',
      '생성 시 로고·워터마크'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-104': {
    title: '처짐계 설치·측정 개념도',
    webp: 'assets/images/technology/IMG-104_처짐계-설치-측정-개념도_LVDT와이어.webp',
    alt: '처짐계 설치·측정 개념도 - LVDT·와이어 — 구조 처짐 전용',
    caption: '처짐계 — LVDT·와이어 (≠침하판)',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-104',
    prohibitedErrors: [
      '침하계·침하판',
      '지반 침하 단면'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-105': {
    title: '교량 케이블 장력 계측도',
    webp: 'assets/images/technology/IMG-105_교량-케이블장력-계측도_사장교주파수법.webp',
    alt: '교량 케이블 장력 계측도 - 사장교·주파수법 · ≠앵커 로드셀',
    caption: '케이블 장력 — f→T·주파수법',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-105',
    prohibitedErrors: [
      '어스앵커 로드셀',
      'IMG-004 재사용'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-106': {
    title: '케이블장력계 설치 개념도',
    webp: 'assets/images/technology/IMG-106_케이블장력계-주파수법-설치-개념도.webp',
    alt: '케이블장력계 설치 개념도 - 노출 케이블 ACC·주파수',
    caption: '케이블장력계 — ≠하중계',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-106',
    prohibitedErrors: [
      '하중계=케이블장력',
      '버팀보 로드셀',
      '진동현식·VW 라벨 (METHOD-01)'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-107': {
    title: '교량 변형률·응력 계측도',
    webp: 'assets/images/technology/IMG-107_교량-변형률-응력-계측도_PSC강재휨응력.webp',
    alt: '교량 변형률·응력 계측도 - PSC·강재 휨·전단 SG',
    caption: '교량 변형률 — 휨·전단·온도 보정',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-107',
    prohibitedErrors: [
      '침하계 단면',
      '흙막이 배경'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-108': {
    title: '무응력계 설치 개념도',
    webp: 'assets/images/technology/IMG-108_무응력계-설치-개념도_크리프보정.webp',
    alt: '무응력계 설치 개념도 - 크리프·건조수축 보정',
    caption: '무응력계 — 응력 0 매립',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-108',
    prohibitedErrors: [
      '일반 SG와 동일 캡션'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-109': {
    title: '교량 풍향·풍속 계측도',
    webp: 'assets/images/technology/IMG-109_교량-풍향풍속-계측도_주탑교면.webp',
    alt: '교량 풍향·풍속 계측도 - 주탑·교면 · 진동 연계',
    caption: '교량 풍하중 — 주탑·풍속 벡터',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-109',
    prohibitedErrors: [
      '사면 강우 hero만',
      '지하수위계 단독'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-110': {
    title: '교량 받침부 변위 계측도',
    webp: 'assets/images/technology/IMG-110_교량-받침부-변위-계측도_슬라이드회전.webp',
    alt: '교량 받침부 변위 계측도 - 받침 슬라이드·회전 — ≠신축이음·3축 GNSS',
    caption: '받침부 변위 — 슬라이드·회전',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-110',
    prohibitedErrors: [
      'X/Y/Z 3축 주계측',
      '종·횡변위 제목',
      '신축이음 핑거형 hero',
      'GNSS 절대좌표 혼합'
    ],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-111': {
    title: '터널 건설기간 계측 개념도',
    webp: 'assets/images/technology/IMG-111_external.webp',
    alt: '터널 건설기간 계측 개념도 - 굴착·지보 단계 내공·천단·지표 변위 — 운행철도 상부',
    caption: '터널 건설기간 계측 — 내공·천단·지표',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-111',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-112': {
    title: '철도·고속철도 건설기간 계측 개념도',
    webp: 'assets/images/technology/IMG-112_external.webp',
    alt: '철도·고속철도 건설기간 계측 개념도 - 道床·노반·궤도 시공 단계 침하·변위',
    caption: '철도 건설기간 계측 — 노반·궤도',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-112',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  },
  'IMG-113': {
    title: '댐·제방 건설기간 계측 개념도',
    webp: 'assets/images/technology/IMG-113_external.webp',
    alt: '댐·제방 건설기간 계측 개념도 - 축조·성토 단계 수압·침하·로거 — ≠운영기 누수',
    caption: '댐 건설기간 계측 — 축조·원격계측',
    status: 'reviewed',
    reviewGrade: 'PASS',
    reviewDoc: 'docs/IMAGE_REVIEW_LOG.md#IMG-113',
    prohibitedErrors: [],
    wireframeReplace: false,
    requiresReaudit: false,
    productionMethod: 'ai-reviewed'
  }
};

const DEFAULT_OG = 'assets/images/technology/IMG-058_통합-계측-플랫폼-아키텍처_센서로거서버DB웹모바일.webp';
const APPROVED_GRADES = new Set(['PASS', 'MINOR_FIX']);

/** 운영 노출 허용 여부 — TECHNICAL_IMAGE_STANDARD.md */
export function isImageApproved(asset) {
  if (!asset) return false;
  if (asset.wireframeReplace) return false;
  if (asset.requiresReaudit) return false;
  return asset.status === 'reviewed' && APPROVED_GRADES.has(asset.reviewGrade);
}

export function resolveImage(imageId, overrides) {
  if (!imageId && overrides?.imageId) imageId = overrides.imageId;
  const asset = imageId ? IMAGE_ASSETS[imageId] : null;
  if (!asset) return null;
  if (!isImageApproved(asset)) return null;
  const primary = asset.webp;
  const resolved = {
    src: primary,
    alt: asset.alt,
    caption: asset.caption,
    imageId: imageId,
    title: asset.title,
    status: asset.status,
    reviewGrade: asset.reviewGrade,
    reviewDoc: asset.reviewDoc
  };
  if (overrides?.caption) resolved.caption = overrides.caption;
  if (overrides?.figureNo != null) resolved.figureNo = overrides.figureNo;
  return resolved;
}

export function defaultOgImage() {
  return DEFAULT_OG;
}
